version: '3.8'

services:
  api:
    container_name: projet_picsou_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:i0h70JmTynW9@db:5432/projet_picsou_bdd
      - RUST_BACKTRACE=1
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: projet_picsou_bdd
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: i0h70JmTynW9
      POSTGRES_DB: projet_picsou_bdd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  postgres-data:
