version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: projet_picsou_bdd
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: i0h70JmTynW9
      POSTGRES_DB: projet_picsou_bdd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
