version: '3.8'

services:
  api:
    container_name: projet_picsou_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RUST_BACKTRACE=1

