CREATE TABLE friends (
    id SERIAL PRIMARY KEY,
    user1_id INT NOT NULL,
    user2_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (user1_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (user2_id) REFERENCES users(id)ON DELETE CASCADE
);

CREATE TRIGGER set_timestamp_friends
    BEFORE UPDATE ON FRIENDS
    FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
