ALTER TABLE groups_users
    DROP CONSTRAINT IF EXISTS fk_user,
    DROP CONSTRAINT IF EXISTS fk_group,
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_group FOREIGN KEY (id_group) REFERENCES groups(id) ON DELETE CASCADE;