name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: connect to raspberry pi, pull last version and execute docker compose
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/projet_picsou_api/
            git pull origin main
            docker-compose down
            docker-compose up --build -d
