name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: connect to raspberry pi, pull last version and execute docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: secrets.SSH_USER
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/projet_picsou_api/
            git pull origin main
            docker-compose down
            docker-compose up --build -d
